'use client';

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { CalendarPlus, CheckCircle2, Clock3, Loader2 } from 'lucide-react';
import { PageHeader } from '@/components/page-header';
import { ManagerAndAbove } from '@/components/RoleGuard';
import { useAccountScope } from '@/lib/account-scope';

const field = 'min-h-11 w-full rounded-lg border border-line bg-coal px-3 text-base text-cream focus:border-ember focus:outline-none';
const day = 86_400_000;
const isoDay = (date: Date) => date.toISOString().slice(0, 10);
const startOfWeek = () => { const date = new Date(); date.setHours(12,0,0,0); date.setDate(date.getDate() - ((date.getDay() + 6) % 7)); return isoDay(date); };

export default function WorkforcePage() {
  const { selectedAccountId } = useAccountScope();
  const [start, setStart] = useState(startOfWeek());
  const end = useMemo(() => isoDay(new Date(new Date(`${start}T12:00:00`).getTime() + 6 * day)), [start]);
  const [data, setData] = useState<any>({ employees: [], locations: [], schedules: [], entries: [] });
  const [form, setForm] = useState({ employee_id: '', location_id: '', starts_at: '', ends_at: '', notes: '' });
  const [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [message, setMessage] = useState('');
  const suffix = selectedAccountId ? `&account_id=${selectedAccountId}` : '';

  const load = useCallback(async () => { setLoading(true); const response = await fetch(`/api/workforce?start=${start}&end=${end}${suffix}`, { cache: 'no-store' }); const body = await response.json(); if (response.ok) setData(body); else setMessage(body.error); setLoading(false); }, [start, end, suffix]);
  useEffect(() => { load(); }, [load]);

  const employee = (id: string) => data.employees.find((item: any) => item.id === id)?.full_name || 'Unknown employee';
  const location = (id: string) => data.locations.find((item: any) => item.id === id)?.name || 'Any location';
  const completed = data.entries.filter((entry: any) => entry.clocked_out_at);
  const pending = completed.filter((entry: any) => entry.approval_status !== 'approved');
  const totalHours = completed.reduce((sum: number, entry: any) => sum + (new Date(entry.clocked_out_at).getTime() - new Date(entry.clocked_in_at).getTime()) / 3_600_000, 0);

  async function createShift(event: FormEvent) { event.preventDefault(); setBusy(true); setMessage(''); const response = await fetch(`/api/workforce?${suffix.slice(1)}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, starts_at: new Date(form.starts_at).toISOString(), ends_at: new Date(form.ends_at).toISOString() }) }); const body = await response.json(); setBusy(false); if (!response.ok) { setMessage(body.error); return; } setForm({ employee_id: '', location_id: '', starts_at: '', ends_at: '', notes: '' }); setMessage('Shift added.'); load(); }
  async function approve(ids: string[], status = 'approved') { if (!ids.length) return; setBusy(true); const response = await fetch(`/api/workforce?${suffix.slice(1)}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ entry_ids: ids, status }) }); const body = await response.json(); setBusy(false); setMessage(response.ok ? `${body.updated} time ${body.updated === 1 ? 'entry' : 'entries'} approved.` : body.error); load(); }

  return <ManagerAndAbove><div><PageHeader title="Scheduling & Timesheets" description="Plan employee shifts, compare actual time, and approve completed time entries." />
    <div className="mb-5 flex flex-col gap-3 rounded-xl border border-line bg-smoke p-4 sm:flex-row sm:items-end sm:justify-between"><label className="text-xs text-mist">Week beginning<input type="date" value={start} onChange={event=>setStart(event.target.value)} className={`${field} mt-1 sm:w-52`} /></label><div className="grid grid-cols-2 gap-3 sm:flex"><div className="rounded-lg bg-hover px-4 py-2"><p className="text-xs text-mist">Recorded hours</p><p className="text-xl font-bold text-cream">{totalHours.toFixed(2)}</p></div><div className="rounded-lg bg-hover px-4 py-2"><p className="text-xs text-mist">Pending review</p><p className="text-xl font-bold text-cream">{pending.length}</p></div></div></div>
    <form onSubmit={createShift} className="mb-6 grid gap-3 rounded-xl border border-line bg-smoke p-4 sm:grid-cols-2 lg:grid-cols-3"><div className="flex items-center gap-2 sm:col-span-2 lg:col-span-3"><CalendarPlus className="h-5 w-5 text-ember"/><h2 className="font-semibold text-cream">Create a shift</h2></div><select required value={form.employee_id} onChange={event=>setForm({...form,employee_id:event.target.value})} className={field}><option value="">Select employee</option>{data.employees.map((item:any)=><option key={item.id} value={item.id}>{item.full_name}</option>)}</select><select value={form.location_id} onChange={event=>setForm({...form,location_id:event.target.value})} className={field}><option value="">Any location</option>{data.locations.map((item:any)=><option key={item.id} value={item.id}>{item.name}</option>)}</select><input required type="datetime-local" aria-label="Shift start" value={form.starts_at} onChange={event=>setForm({...form,starts_at:event.target.value})} className={field}/><input required type="datetime-local" aria-label="Shift end" value={form.ends_at} onChange={event=>setForm({...form,ends_at:event.target.value})} className={field}/><input placeholder="Shift notes (optional)" value={form.notes} onChange={event=>setForm({...form,notes:event.target.value})} className={field}/><button disabled={busy} className="min-h-11 rounded-lg bg-ember px-5 font-semibold text-white disabled:opacity-60">{busy?<Loader2 className="mx-auto h-5 w-5 animate-spin"/>:'Add Shift'}</button></form>
    {message&&<p role="status" className="mb-4 rounded-lg border border-line bg-hover p-3 text-sm text-mist">{message}</p>}
    <section className="mb-6 rounded-xl border border-line bg-smoke"><div className="border-b border-line p-4"><h2 className="font-semibold text-cream">Scheduled shifts · {start} to {end}</h2></div>{loading?<Loader2 className="mx-auto my-10 animate-spin text-ember"/>:data.schedules.length?<div className="divide-y divide-line">{data.schedules.map((shift:any)=><div key={shift.id} className="grid gap-1 p-4 sm:grid-cols-[1.4fr_1fr_1fr]"><div><p className="font-medium text-cream">{employee(shift.employee_id)}</p><p className="text-xs text-mist">{location(shift.location_id)}</p></div><p className="text-sm text-mist">{new Date(shift.starts_at).toLocaleDateString([], {weekday:'short',month:'short',day:'numeric'})}</p><p className="text-sm text-mist">{new Date(shift.starts_at).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}–{new Date(shift.ends_at).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}</p></div>)}</div>:<p className="p-8 text-center text-sm text-mist">No shifts scheduled for this week.</p>}</section>
    <section className="rounded-xl border border-line bg-smoke"><div className="flex flex-col gap-3 border-b border-line p-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold text-cream">Timesheet review</h2><p className="text-xs text-mist">Only completed shifts can be approved.</p></div><button disabled={busy||!pending.length} onClick={()=>approve(pending.map((entry:any)=>entry.id))} className="flex min-h-11 items-center justify-center gap-2 rounded-lg bg-ember px-5 text-sm font-semibold text-white disabled:opacity-50"><CheckCircle2 className="h-4 w-4"/>Approve all pending</button></div>{loading?<Loader2 className="mx-auto my-10 animate-spin text-ember"/>:completed.length?<div className="divide-y divide-line">{completed.map((entry:any)=>{const hours=(new Date(entry.clocked_out_at).getTime()-new Date(entry.clocked_in_at).getTime())/3_600_000;return <div key={entry.id} className="grid gap-3 p-4 sm:grid-cols-[1.4fr_1fr_auto] sm:items-center"><div><p className="font-medium text-cream">{employee(entry.employee_id)}</p><p className="text-xs text-mist">{new Date(entry.clocked_in_at).toLocaleString()} · {hours.toFixed(2)} hours</p></div><span className={`w-fit rounded-full px-2.5 py-1 text-xs font-semibold ${entry.approval_status==='approved'?'bg-green-900/30 text-green-400':'bg-amber-900/30 text-amber-300'}`}>{entry.approval_status==='approved'?'Approved':'Pending'}</span>{entry.approval_status!=='approved'&&<button disabled={busy} onClick={()=>approve([entry.id])} className="min-h-10 rounded-lg border border-line px-4 text-sm text-cream">Approve</button>}</div>})}</div>:<div className="p-8 text-center"><Clock3 className="mx-auto h-8 w-8 text-mist/40"/><p className="mt-2 text-sm text-mist">No completed time entries for this week.</p></div>}</section>
  </div></ManagerAndAbove>;
}
