'use client';
import { FormEvent,useCallback,useEffect,useState } from 'react';
import { KeyRound,Loader2,Plus,RotateCcw,ShieldCheck } from 'lucide-react';
import { PageHeader } from '@/components/page-header';
import { OwnerOnly } from '@/components/RoleGuard';
import { useAccountScope } from '@/lib/account-scope';
const inputClass='w-full rounded-lg bg-coal border border-line px-3 py-2.5 text-sm text-cream focus:border-ember focus:outline-none';
const blankEmployee={employee_code:'',full_name:'',email:'',mobile:'',role:'staff',location_id:'',temporary_password:''};
export default function StaffAdmin(){
  const {selectedAccountId}=useAccountScope();
  const [data,setData]=useState<any>({employees:[],locations:[],events:[]});
  const [employeeOpen,setEmployeeOpen]=useState(false),[locationOpen,setLocationOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const [employeeForm,setEmployeeForm]=useState<any>(blankEmployee),[locationForm,setLocationForm]=useState({name:'',type:'restaurant'});
  const suffix=selectedAccountId?`?account_id=${selectedAccountId}`:'';
  const load=useCallback(async()=>{const response=await fetch(`/api/admin/staff${suffix}`);if(response.ok)setData(await response.json())},[suffix]);
  useEffect(()=>{load()},[load]);
  async function createEmployee(event:FormEvent){event.preventDefault();setBusy(true);setError('');const response=await fetch(`/api/admin/staff${suffix}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(employeeForm)});const body=await response.json();setBusy(false);if(!response.ok){setError(body.error);return}setEmployeeOpen(false);setEmployeeForm(blankEmployee);load()}
  async function createLocation(event:FormEvent){event.preventDefault();setBusy(true);setError('');const response=await fetch(`/api/admin/staff${suffix}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({resource:'location',...locationForm})});const body=await response.json();setBusy(false);if(!response.ok){setError(body.error);return}setLocationOpen(false);setLocationForm({name:'',type:'restaurant'});load()}
  async function reset(employeeId:string,kind:'pin'|'password'|'unlock'){const body:any={employee_id:employeeId};if(kind==='pin'){const value=prompt('Enter the employee’s new 6-digit PIN:');if(!value)return;body.new_pin=value}if(kind==='password'){const value=prompt('Enter a temporary password (at least 8 characters):');if(!value)return;body.temporary_password=value}const response=await fetch(`/api/admin/staff${suffix}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!response.ok)alert((await response.json()).error);load()}
  return <OwnerOnly><div>
    <PageHeader title="Staff & PINs" description="Create staff credentials and work locations, reset access, and review lock status."/>
    <div className="mb-4 flex flex-wrap justify-end gap-2"><button onClick={()=>{setLocationOpen(value=>!value);setEmployeeOpen(false);setError('')}} className="flex items-center gap-2 rounded-lg border border-line px-4 py-2.5 text-sm font-semibold text-cream"><Plus className="h-4 w-4"/>Add Location</button><button onClick={()=>{setEmployeeOpen(value=>!value);setLocationOpen(false);setError('')}} className="flex items-center gap-2 rounded-lg bg-ember px-4 py-2.5 text-sm font-semibold text-white"><Plus className="h-4 w-4"/>Create Staff Login</button></div>
    {locationOpen&&<form onSubmit={createLocation} className="mb-6 grid gap-3 rounded-xl border border-line bg-hover p-5 sm:grid-cols-[1fr_220px_auto]"><input required className={inputClass} placeholder="Location name" value={locationForm.name} onChange={event=>setLocationForm({...locationForm,name:event.target.value})}/><select className={inputClass} value={locationForm.type} onChange={event=>setLocationForm({...locationForm,type:event.target.value})}><option value="restaurant">Restaurant</option><option value="food_truck">Food truck</option></select><button disabled={busy} className="rounded-lg bg-ember px-5 py-2.5 font-semibold text-white disabled:opacity-60">{busy?'Saving…':'Add location'}</button>{error&&<p className="text-sm text-red-400 sm:col-span-3">{error}</p>}</form>}
    {employeeOpen&&<form onSubmit={createEmployee} className="mb-6 grid gap-3 rounded-xl border border-line bg-hover p-5 sm:grid-cols-2"><input required className={inputClass} placeholder="Employee ID" value={employeeForm.employee_code} onChange={event=>setEmployeeForm({...employeeForm,employee_code:event.target.value})}/><input required className={inputClass} placeholder="Full name" value={employeeForm.full_name} onChange={event=>setEmployeeForm({...employeeForm,full_name:event.target.value})}/><input required={employeeForm.role==='manager'} className={inputClass} type="email" placeholder={employeeForm.role==='manager'?'Team email (required for manager access)':'Email (optional)'} value={employeeForm.email} onChange={event=>setEmployeeForm({...employeeForm,email:event.target.value})}/><input className={inputClass} placeholder="Mobile (optional)" value={employeeForm.mobile} onChange={event=>setEmployeeForm({...employeeForm,mobile:event.target.value})}/><select className={inputClass} value={employeeForm.role} onChange={event=>setEmployeeForm({...employeeForm,role:event.target.value})}><option value="staff">Staff</option><option value="lead">Lead</option><option value="manager">Manager</option></select><select className={inputClass} value={employeeForm.location_id} onChange={event=>setEmployeeForm({...employeeForm,location_id:event.target.value})}><option value="">Any location</option>{data.locations.map((location:any)=><option key={location.id} value={location.id}>{location.name} · {location.type==='food_truck'?'Food truck':'Restaurant'}</option>)}</select>{employeeForm.role==='manager'&&<p className="rounded-lg border border-amber-700/50 bg-amber-950/30 p-3 text-xs leading-5 text-amber-200 sm:col-span-2">First create the person as a Manager under Team. Use that same email here so their employee ID and PIN can open the manager workspace.</p>}<input required minLength={8} className={inputClass} type="password" placeholder="Temporary password (8+ characters)" value={employeeForm.temporary_password} onChange={event=>setEmployeeForm({...employeeForm,temporary_password:event.target.value})}/><button disabled={busy} className="rounded-lg bg-ember p-2.5 font-semibold text-white disabled:opacity-60">{busy?<Loader2 className="mx-auto h-5 w-5 animate-spin"/>:'Create account'}</button>{error&&<p className="text-sm text-red-400 sm:col-span-2">{error}</p>}</form>}
    <div className="mb-6 rounded-xl border border-line bg-hover p-5"><h2 className="text-sm font-semibold text-cream">Work locations</h2><div className="mt-3 flex flex-wrap gap-2">{data.locations.length?data.locations.map((location:any)=><span key={location.id} className="rounded-full border border-line bg-coal px-3 py-1.5 text-xs text-mist">{location.name} · {location.type==='food_truck'?'Food truck':'Restaurant'}</span>):<p className="text-sm text-amber-400">No locations yet. Add a restaurant or food truck before staff sign in.</p>}</div></div>
    <div className="overflow-hidden rounded-xl border border-line bg-hover"><div className="hidden border-b border-line px-5 py-3 text-xs uppercase text-mist md:grid md:grid-cols-[2fr_1fr_1fr_auto]"><span>Employee</span><span>Role</span><span>Access</span><span>Actions</span></div>{data.employees.map((employee:any)=><div key={employee.id} className="grid gap-3 border-b border-line px-5 py-4 last:border-0 md:grid-cols-[2fr_1fr_1fr_auto] md:items-center"><div><p className="font-medium text-cream">{employee.full_name}</p><p className="text-xs text-mist">ID {employee.employee_code}{employee.email?` · ${employee.email}`:''}</p></div><p className="text-sm capitalize text-mist">{employee.role}</p><div className="text-xs">{employee.locked_until&&new Date(employee.locked_until)>new Date()?<span className="text-red-400">Locked</span>:employee.must_set_pin?<span className="text-amber-400">PIN setup required</span>:<span className="text-green-400">Active PIN</span>}</div><div className="flex gap-2"><button title="Reset PIN" onClick={()=>reset(employee.id,'pin')} className="rounded-lg border border-line p-2 text-mist hover:text-cream"><KeyRound className="h-4 w-4"/></button><button title="Set temporary password" onClick={()=>reset(employee.id,'password')} className="rounded-lg border border-line p-2 text-mist hover:text-cream"><RotateCcw className="h-4 w-4"/></button><button title="Unlock" onClick={()=>reset(employee.id,'unlock')} className="rounded-lg border border-line p-2 text-mist hover:text-cream"><ShieldCheck className="h-4 w-4"/></button></div></div>)}{!data.employees.length&&<p className="p-10 text-center text-sm text-mist">No staff login accounts yet.</p>}</div>
  </div></OwnerOnly>
}
